### ISSUE TITLE
Trailing slashes in cmdline?

### ISSUE THREAD

**Issue by PowerUser64** [hrsh7th/cmp-path#40]
I have noticed that quite frequently I will get trailing slashes appended to the completions.

---

### Steps to reproduce:

1. Type the name of a directory and press tab

Notice there is a slash appended to the result

![image](https://user-images.githubusercontent.com/24578572/166073572-805dc40e-60a5-4746-8c81-b0055e42e3e5.png)

3. Type a slash to get cmp-path to read from the next directory

But wait, now it's trying to complete from the root directory?

![image](https://user-images.githubusercontent.com/24578572/166073790-13e79f45-f38c-45f9-9b4a-e96a45d1f672.png)

4. Press backspace to remove the slash

Wait, now there are two of every file

![image](https://user-images.githubusercontent.com/24578572/166073875-1440256a-25b7-4c69-83d7-d6bb190ca2c3.png)

---

This doesn't happen in the buffer, only in the cmdline. I have noticed that it works properly sometimes, but it is rare and I don't know what causes it to work properly. Although, I'm pretty sure it has to do with the trailing slash because in the cmdline, a slash is appended, and in the buffer, a slash is not appended.

Is this a known bug or is there a way to solve this?

**Comment by otavioschwanck** [comment]
Same here, if i use with cmp-cmdline, `:e ~/` it does't add the slash, if i try to use just `:e /some/path` it adds the slash, super annoying

**Comment by iwataka** [comment]
I think current `cmp-path` is triggered only by `/` or `.`.
So you should start with one of these characters to use this plugin's feature.

https://github.com/hrsh7th/cmp-path/blob/f244d8c33387b2da8915eabf9d2296a4f4ba3e45/lua/cmp_path/init.lua#L38-L40

For example, without these characters, it behaves like below.
The type of completion candidates becomes `Variable` because `cmp-path` doesn't work properly.

<img width="296" alt="Screen Shot 2022-06-13 at 2 01 28" src="https://user-images.githubusercontent.com/7800796/173244515-3cc3af90-1271-4899-8b7c-bf9f3b52df33.png">

To make it works properly, you should start with `./`, like below.
The type of completion candidates becomes File/Folder, which means `cmp-path` is working.

<img width="296" alt="Screen Shot 2022-06-13 at 2 05 04" src="https://user-images.githubusercontent.com/7800796/173244649-b060c374-7bab-431e-bbd3-735072c22d73.png">

Also, `cmp-path` works with leading `/` and `~/`.

<img width="296" alt="Screen Shot 2022-06-13 at 2 07 30" src="https://user-images.githubusercontent.com/7800796/173244740-8c7aac29-ff72-4a45-ac51-b990d95009b2.png">

<img width="296" alt="Screen Shot 2022-06-13 at 2 08 36" src="https://user-images.githubusercontent.com/7800796/173244795-0a6382a5-c9a3-4a3e-9b3a-537000e6503d.png">

**Comment by PowerUser64** [comment]
After doing some messing around, I figured out it was my configuration that was wrong. I had put some things in the wrong places (lua is confusing lol).

**Comment by PowerUser64** [comment]
Okay, so upon further inspection, adopting part of iwataka's config was only part of the solution. I believe the real problem is that [`cmp-cmdline`](https://github.com/hrsh7th/cmp-cmdline) is completing the path, rather than `cmp-path`, and `cmp-path` is not well-equipped to do so well. So, when additional `/` characters are added and then deleted, it returns double the number of completions because doing `//` on UNIX systems is usually interpreted as a single `/`.

I have no idea how to keep `cmp-cmdline` from trying to do `cmp-path`'s job, but if there is a way to do such a thing, I'm pretty sure it would solve this problem.

I have opened issue hrsh7th/cmp-cmdline#60 to discuss this further, as I can now confirm it is not a problem with `cmp-path`.

**Comment by Hubro** [comment]
![image](https://user-images.githubusercontent.com/597206/187050434-837ae642-1a92-461a-842d-bd46dc1bf104.png)

:exploding_head:
